version: '3'

services:
  product1:
    build: Product_API/
    # depends_on:
    #   - 'database'
    ports:
      - '3001:3001'
  # product1:
  #   build: Product_API/
  #   depends_on:
  #     - 'database'
  #   ports:
  #     - '3002:3001'
  # product2:
  #   build: Product_API/
  #   depends_on:
  #     - 'database'
  #   ports:
  #     - '3003:3001'
  # product3:
  #   build: Product_API/
  #   depends_on:
  #     - 'database'
  #   ports:
  #     - '3004:3001'
  # nginx:
  #   build: ./nginx
  #   ports:
  #     - '3001:3001'
    # depends_on:
    #   - product
    #   - product1
    #   - product2
    #   - product3
#   database:
#     image: mysql:8.0.23
#     restart: always
#     environment:
#       MYSQL_DATABASE: productAPI
#       MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
#     volumes:
#       - db_data:/var/lib/mysql
# volumes:
#   db_data:

# version: '3'

# services:
#   product:
#     build: Product_API/
#     depends_on:
#       - 'database'
#     ports:
#       - '3001:3001'
#   database:
#     image: mysql:8.0.23
#     restart: always
#     environment:
#       MYSQL_DATABASE: productAPI
#       MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
#     volumes:
#       - db_data:/var/lib/mysql
#       - ./Product_API/clean:/tmp
# volumes:
#   db_data:


# version: '3.3'

# services:
#   db:
#     image: library/mysql:8.0.23
#     restart: always
#     environment:
#       MYSQL_DATABASE: productAPI
#       MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
#     ports:
#       # <Port exposed> : < MySQL Port running inside container>
#       - '3306:3306'
#     expose:
#       # Opens port 3306 on the container
#       - '3306'
#       # Where our data will be persisted
#     volumes:
#       - my-db:/var/lib/mysql
# # Names our volume
# volumes:
#   my-db:

# version: '3'

# services:
#   product:
#     image: ochaart/sdc_product
#     ports:
#       - '3001:3001'
#     expose:
#       - '3001'